### PR TITLE
(fix): Remove double-kill bug in Windows process termination (#777)

### LINKED ISSUE #777: BUG Windows doesn't kill processes properly
https://github.com/user-attachments/assets/88cbe7e7-5d10-467c-bd80-3b606f60b355

The config files are all defaults, and I've also seen send_interrupt Windows is not supported.

The operating system is Windos11 and the air version is 1.62.0

The feedback is from the translation, please forgive me if the expression is not clear.

### PR DESCRIPTION
**Pull request by its-kios09**
Problems fixed:
- Removed double TASKKILL execution when SendInterrupt is enabled
- Simplified kill logic to match Linux behavior (single kill command)
- Added console window hiding for cleaner UX (no flashing windows)
- Switched from PowerShell to cmd.exe for better performance
- Improved logging to match Linux output format
- Better error handling for already-terminated processes

The previous code would run TASKKILL twice when SendInterrupt was enabled, or handle it inconsistently when disabled. This caused processes to not be properly terminated, leading to port conflicts and orphaned processes as reported in #777.

Testing on Linux shows clean process transitions with no port conflicts. Windows users requested to test and verify the fix.

Fixes #777

### CODE REVIEW

**Comment by its-kios09** [comment]
@xiantang  ping

**Comment by xiantang** [comment]
Hello yesterday I just install a window 10 on my old pc, I'll test if I find time

File: runner/util_windows.go [hunk 1]
```diff
@@ -1,53 +1,90 @@
...
 	"strings"
-	"time"
+	"syscall"
 )
 
 func (e *Engine) killCmd(cmd *exec.Cmd) (pid int, err error) {
 	pid = cmd.Process.Pid
-	// https://stackoverflow.com/a/44551450
-	kill := exec.Command("TASKKILL", "/T", "/F", "/PID", strconv.Itoa(pid))
+	e.runnerLog("trying to kill pid %d, cmd %v", pid, cmd.Args)
```
Comment (xiantang) [inline runner/util_windows.go]: do we need this log? We don't have this runner log on other platform, if u want can put in debug log

File: runner/util_windows.go [hunk 2]
```diff
@@ -1,53 +1,90 @@
...
 	if e.config.Build.SendInterrupt {
-		if err = kill.Run(); err != nil {
-			return
-		}
-		time.Sleep(e.config.killDelay())
-	}
-	err = kill.Run()
-	// Wait releases any resources associated with the Process.
-	_, _ = cmd.Process.Wait()
+		e.mainLog("send_interrupt is not supported on Windows, using TASKKILL instead")
```
Comment (xiantang) [inline runner/util_windows.go]: Please confirm that windows doesn't have Ctrl-c behaviour

File: runner/util_windows.go [hunk 3]
```diff
@@ -1,53 +1,90 @@
...
+	}
+
+	// Use TASKKILL to kill the entire process tree
+	// /F = Force termination
+	// /T = Terminate all child processes
+	// /PID = Process ID to kill
+	e.runnerLog("sending TASKKILL to process tree")
```
Comment (xiantang) [inline runner/util_windows.go]: Please don't put detailed log in runner log

**Comment by its-kios09** [comment]
@xiantang I have updated the PR

**Comment by its-kios09** [comment]
@xiantang If you have any issue pending please tag me i can help

**Comment by xiantang** [comment]
let me try to reproduce in local

**Comment by xiantang** [comment]
look good to me, but i cant reproduce the orphaned process in the old version, anyway let me merge it

**Comment by xiantang** [comment]
@its-kios09 https://github.com/air-verse/air/issues/707 please aware of this issue

**Comment by xiantang** [comment]
image
air will make a weird sound, https://github.com/air-verse/air-reproducible-example/tree/main/issue-707-windows-cmd-parse

**Comment by xiantang** [comment]
so i revert first
